# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def pod_test
  pod 'FBSDKCoreKit', '~>6.5.2'
  pod 'FBSDKShareKit', '~>6.5.2'
  pod 'FBSDKLoginKit', '~>6.5.2'
  pod 'GoogleSignIn', '5.0.2'
  pod 'Firebase/AdMob'
end

target 'MyCocoaPodsTest iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyCocoaPodsTest iOS
  pod_test
end
